{% set name = "crc32c" %}
{% set version = "2.2.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3d058e7a5e37e4985d1a7ad4cb702bca56b490daa658d4851377d13ead8b435e

build:
  number: 2
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - crc32c


about:
  home: https://github.com/ICRAR/crc32c
  license: GNU Lesser General Public v2 or later (LGPLv2+)
  license_family: LGPL
  license_file: LICENSE
  summary: A python package exposing the Intel SSE4.2 CRC32C instruction

extra:
  recipe-maintainers:
    - pinin4fjords
