{% set name = "crc32c" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8799fc1555497be25d654096a18ef79811e98ce1e1be3048ddda2f2f5a84edd2

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - crc32c


about:
  home: https://github.com/ICRAR/crc32c
  license: GNU Lesser General Public v2 or later (LGPLv2+)
  license_family: LGPL
  license_file: LICENSE
  summary: A python package exposing the Intel SSE4.2 CRC32C instruction

extra:
  recipe-maintainers:
    - pinin4fjords
