{% set name = "crc32c" %}
{% set version = "2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2cb2076843feffbbffd9a8d7e87b58f0b430872c083eab2a7f52b83b6e882ca9

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - crc32c


about:
  home: https://github.com/ICRAR/crc32c
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: A python package exposing the Intel SSE4.2 CRC32C instruction

extra:
  recipe-maintainers:
    - pinin4fjords
