schema_version: 1

context:
  name: crc32c
  version: "2.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: d6d2ae0299a417e5fb2e3641838cec34a23778a62fb4ce928792366476c1983b

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python

tests:
  - python:
      imports:
        - crc32c
      pip_check: true

about:
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: A python package exposing the Intel SSE4.2 CRC32C instruction
  homepage: https://github.com/ICRAR/crc32c

extra:
  recipe-maintainers:
    - jhamman
    - pinin4fjords
    - synapticarbors
